// <auto-generated />
using System;
using ExpensesTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpensesTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240411064011_AddExpenseTrackerTable")]
    partial class AddExpenseTrackerTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpensesTracker.Models.ExpenseModel", b =>
                {
                    b.Property<int>("ET_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ET_Id"));

                    b.Property<double>("ET_Amount")
                        .HasColumnType("float");

                    b.Property<string>("ET_Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("ET_Date")
                        .HasColumnType("date");

                    b.Property<string>("ET_Expense_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ET_RefundYN")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("ET_Id");

                    b.ToTable("ExpenseTracker");
                });
#pragma warning restore 612, 618
        }
    }
}
