// <auto-generated />
using System;
using ExpensesTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpensesTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpensesTracker.Models.ExpenseModel", b =>
                {
                    b.Property<int>("ET_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ET_Id"));

                    b.Property<double>("ET_Amount")
                        .HasColumnType("float");

                    b.Property<string>("ET_Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("ET_Date")
                        .HasColumnType("date");

                    b.Property<string>("ET_Expense_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ET_RefundYN")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("ET_Id");

                    b.ToTable("ExpenseTracker");

                    b.HasData(
                        new
                        {
                            ET_Id = 1,
                            ET_Amount = 20.0,
                            ET_Date = new DateOnly(2024, 2, 25),
                            ET_Expense_Name = "test",
                            ET_RefundYN = "N"
                        },
                        new
                        {
                            ET_Id = 2,
                            ET_Amount = 80.0,
                            ET_Date = new DateOnly(2024, 1, 15),
                            ET_Expense_Name = "test",
                            ET_RefundYN = "N"
                        },
                        new
                        {
                            ET_Id = 3,
                            ET_Amount = 50.0,
                            ET_Date = new DateOnly(2024, 1, 22),
                            ET_Expense_Name = "test",
                            ET_RefundYN = "Y"
                        },
                        new
                        {
                            ET_Id = 4,
                            ET_Amount = 30.0,
                            ET_Date = new DateOnly(2024, 2, 28),
                            ET_Expense_Name = "test",
                            ET_RefundYN = "Y"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
